### ISSUE TITLE
Finish the readme.md with a project summary and instructions

### ISSUE THREAD

**Issue by fleurvanvugt** [course-dprep/movie-runtimes-on-average-rating_IMDB#5]
__Deliverables__
- Summarize the main results of our project in the readme.md
- Include instructions to potential contributors / replicators on how to run the project

**Comment by lindseycoover** [comment]
Outline for the readme.md from https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/document-data/readme-best-practices/

# Project title

A subtitle that describes your project, e.g., research question


## Motivation

Motivate your research question or business problem. Clearly explain which problem is solved.


## Method and results

First, introduce and motivate your chosen method, and explain how it contributes to solving the research question/business problem.

Second, summarize your results concisely. Make use of subheaders where appropriate.


## Repository overview

Provide an overview of the directory structure and files, for example:

├── README.md
├── data
├── gen
│   ├── analysis
│   ├── data-preparation
│   └── paper
└── src
    ├── analysis
    ├── data-preparation
    └── paper


## Running instructions

Explain to potential users how to run/replicate your workflow. If necessary, touch upon the required input data, which secret credentials are required (and how to obtain them), which software tools are needed to run the workflow (including links to the installation instructions), and how to run the workflow.


## More resources

Point interested users to any related literature and/or documentation.


## About

Explain who has contributed to the repository. You can say it has been part of a class you've taken at Tilburg University.
